spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: cai
        login-password: cai
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      validation-query: SELECT x
      test-on-borrow: false
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      time-between-log-stats-millis:  300000